#!/bin/bash
#SBATCH --job-name="spacesavers2"
#SBATCH --mail-type=BEGIN,END
#SBATCH --mem=120g
#SBATCH --partition="ccr,norm"
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=32


cd $SLURM_SUBMIT_DIR
dt=$(date +%Y%m%d)
SPACESAVERS2DIR="/data/CCBR_Pipeliner/bin/spacesavers2/develop"
#OUTDIR="/data/CBLCCBR/kopardevn_tmp/spacesavers2_testing_CCBR_${dt}"
OUTDIR="/data/CCBR_Pipeliner/userdata/spacesavers2/${dt}"

if [ ! -d $OUTDIR ];then mkdir -p $OUTDIR;fi

${SPACESAVERS2DIR}/bin/spacesavers2_e2e -i /data/CCBR -o $OUTDIR -q 200 -p 32
# delete the largest file to save space
rm -f ${OUTDIR}/*.catalog
