#!/bin/bash
#SBATCH --job-name="spacesavers2"
#SBATCH --mail-type=BEGIN,END
#SBATCH --mem=120g
#SBATCH --partition="ccr,norm"
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=32


cd $SLURM_SUBMIT_DIR
dt=$(date +%Y%m%d)
SPACESAVERS2DIR="/data/CCBR_Pipeliner/bin/spacesavers2/release_v0.6"
OUTDIR="/data/CBLCCBR/kopardevn_tmp/spacesavers2_testing_CCBR_${dt}"

if [ ! -d $OUTDIR ];then mkdir -p $OUTDIR;fi
# ensure that python 3.11, python library xxhash and gnuparallel are in path
# this is currently biowulf specific but can be replaced to your case
. "/data/CCBR_Pipeliner/db/PipeDB/Conda/etc/profile.d/conda.sh"
conda activate py311
export PATH=${SPACESAVERS2DIR}:$PATH

spacesavers2_e2e -i /data/CCBR -o $OUTDIR -q 200 -p 32
